//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

internal class ConfigIpiSwig : ConfigBaseSwig {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ConfigIpiSwig(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConfigIpiSwig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConfigIpiSwig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IpIntelligenceEngineModulePINVOKE.delete_ConfigIpiSwig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ConfigIpiSwig() : this(IpIntelligenceEngineModulePINVOKE.new_ConfigIpiSwig(), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setHighPerformance() {
    IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_setHighPerformance(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBalanced() {
    IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_setBalanced(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBalancedTemp() {
    IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_setBalancedTemp(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setLowMemory() {
    IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_setLowMemory(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMaxPerformance() {
    IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_setMaxPerformance(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setConcurrency(ushort concurrency) {
    IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_setConcurrency(swigCPtr, concurrency);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public CollectionConfigSwig getStrings() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getStrings(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getComponents() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getComponents(swigCPtr), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getMaps() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getMaps(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getProperties() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getProperties(swigCPtr), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getValues() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getValues(swigCPtr), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getProfiles() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getProfiles(swigCPtr), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getGraphs() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getGraphs(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getProfileGroups() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getProfileGroups(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getProfileOffsets() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getProfileOffsets(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getPropertyTypes() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getPropertyTypes(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollectionConfigSwig getGraph() {
    CollectionConfigSwig ret = new CollectionConfigSwig(IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getGraph(swigCPtr), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort getConcurrency() {
    ushort ret = IpIntelligenceEngineModulePINVOKE.ConfigIpiSwig_getConcurrency(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
