//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

public enum IpTypeSwig {
  FIFTYONE_DEGREES_IP_TYPE_INVALID = 0,
  FIFTYONE_DEGREES_IP_TYPE_IPV4 = 4,
  FIFTYONE_DEGREES_IP_TYPE_IPV6 = 6
}

}
