//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

internal class WeightedIntListSwig : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<WeightedValueIntSwig>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WeightedIntListSwig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WeightedIntListSwig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WeightedIntListSwig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WeightedIntListSwig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IpIntelligenceEngineModulePINVOKE.delete_WeightedIntListSwig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WeightedIntListSwig(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueIntSwig element in c) {
      this.Add(element);
    }
  }

  public WeightedIntListSwig(global::System.Collections.Generic.IEnumerable<WeightedValueIntSwig> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueIntSwig element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public WeightedValueIntSwig this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(WeightedValueIntSwig[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(WeightedValueIntSwig[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, WeightedValueIntSwig[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public WeightedValueIntSwig[] ToArray() {
    WeightedValueIntSwig[] array = new WeightedValueIntSwig[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<WeightedValueIntSwig> global::System.Collections.Generic.IEnumerable<WeightedValueIntSwig>.GetEnumerator() {
    return new WeightedIntListSwigEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new WeightedIntListSwigEnumerator(this);
  }

  public WeightedIntListSwigEnumerator GetEnumerator() {
    return new WeightedIntListSwigEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class WeightedIntListSwigEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<WeightedValueIntSwig>
  {
    private WeightedIntListSwig collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public WeightedIntListSwigEnumerator(WeightedIntListSwig collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public WeightedValueIntSwig Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (WeightedValueIntSwig)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public WeightedIntListSwig() : this(IpIntelligenceEngineModulePINVOKE.new_WeightedIntListSwig__SWIG_0(), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedIntListSwig(WeightedIntListSwig other) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedIntListSwig__SWIG_1(WeightedIntListSwig.getCPtr(other)), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_Clear(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(WeightedValueIntSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_Add(swigCPtr, WeightedValueIntSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_size(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_empty(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_capacity(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_reserve(swigCPtr, n);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedIntListSwig(int capacity) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedIntListSwig__SWIG_2(capacity), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private WeightedValueIntSwig getitemcopy(int index) {
    WeightedValueIntSwig ret = new WeightedValueIntSwig(IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_getitemcopy(swigCPtr, index), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private WeightedValueIntSwig getitem(int index) {
    WeightedValueIntSwig ret = new WeightedValueIntSwig(IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_getitem(swigCPtr, index), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, WeightedValueIntSwig val) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_setitem(swigCPtr, index, WeightedValueIntSwig.getCPtr(val));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(WeightedIntListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_AddRange(swigCPtr, WeightedIntListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedIntListSwig GetRange(int index, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_GetRange(swigCPtr, index, count);
    WeightedIntListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedIntListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, WeightedValueIntSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_Insert(swigCPtr, index, WeightedValueIntSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, WeightedIntListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_InsertRange(swigCPtr, index, WeightedIntListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_RemoveAt(swigCPtr, index);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_RemoveRange(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public static WeightedIntListSwig Repeat(WeightedValueIntSwig value, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_Repeat(WeightedValueIntSwig.getCPtr(value), count);
    WeightedIntListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedIntListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_Reverse__SWIG_0(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_Reverse__SWIG_1(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, WeightedIntListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedIntListSwig_SetRange(swigCPtr, index, WeightedIntListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
