//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

internal class WeightedDoubleListSwig : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<WeightedValueDoubleSwig>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WeightedDoubleListSwig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WeightedDoubleListSwig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WeightedDoubleListSwig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WeightedDoubleListSwig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IpIntelligenceEngineModulePINVOKE.delete_WeightedDoubleListSwig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WeightedDoubleListSwig(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueDoubleSwig element in c) {
      this.Add(element);
    }
  }

  public WeightedDoubleListSwig(global::System.Collections.Generic.IEnumerable<WeightedValueDoubleSwig> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueDoubleSwig element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public WeightedValueDoubleSwig this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(WeightedValueDoubleSwig[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(WeightedValueDoubleSwig[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, WeightedValueDoubleSwig[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public WeightedValueDoubleSwig[] ToArray() {
    WeightedValueDoubleSwig[] array = new WeightedValueDoubleSwig[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<WeightedValueDoubleSwig> global::System.Collections.Generic.IEnumerable<WeightedValueDoubleSwig>.GetEnumerator() {
    return new WeightedDoubleListSwigEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new WeightedDoubleListSwigEnumerator(this);
  }

  public WeightedDoubleListSwigEnumerator GetEnumerator() {
    return new WeightedDoubleListSwigEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class WeightedDoubleListSwigEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<WeightedValueDoubleSwig>
  {
    private WeightedDoubleListSwig collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public WeightedDoubleListSwigEnumerator(WeightedDoubleListSwig collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public WeightedValueDoubleSwig Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (WeightedValueDoubleSwig)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public WeightedDoubleListSwig() : this(IpIntelligenceEngineModulePINVOKE.new_WeightedDoubleListSwig__SWIG_0(), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDoubleListSwig(WeightedDoubleListSwig other) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedDoubleListSwig__SWIG_1(WeightedDoubleListSwig.getCPtr(other)), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_Clear(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(WeightedValueDoubleSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_Add(swigCPtr, WeightedValueDoubleSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_size(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_empty(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_capacity(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_reserve(swigCPtr, n);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDoubleListSwig(int capacity) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedDoubleListSwig__SWIG_2(capacity), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private WeightedValueDoubleSwig getitemcopy(int index) {
    WeightedValueDoubleSwig ret = new WeightedValueDoubleSwig(IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_getitemcopy(swigCPtr, index), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private WeightedValueDoubleSwig getitem(int index) {
    WeightedValueDoubleSwig ret = new WeightedValueDoubleSwig(IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_getitem(swigCPtr, index), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, WeightedValueDoubleSwig val) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_setitem(swigCPtr, index, WeightedValueDoubleSwig.getCPtr(val));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(WeightedDoubleListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_AddRange(swigCPtr, WeightedDoubleListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDoubleListSwig GetRange(int index, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_GetRange(swigCPtr, index, count);
    WeightedDoubleListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedDoubleListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, WeightedValueDoubleSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_Insert(swigCPtr, index, WeightedValueDoubleSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, WeightedDoubleListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_InsertRange(swigCPtr, index, WeightedDoubleListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_RemoveAt(swigCPtr, index);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_RemoveRange(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public static WeightedDoubleListSwig Repeat(WeightedValueDoubleSwig value, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_Repeat(WeightedValueDoubleSwig.getCPtr(value), count);
    WeightedDoubleListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedDoubleListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_Reverse__SWIG_0(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_Reverse__SWIG_1(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, WeightedDoubleListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedDoubleListSwig_SetRange(swigCPtr, index, WeightedDoubleListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
