//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

internal class WeightedUTF8StringListSwig : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<WeightedValueUTF8StringSwig>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WeightedUTF8StringListSwig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WeightedUTF8StringListSwig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WeightedUTF8StringListSwig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WeightedUTF8StringListSwig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IpIntelligenceEngineModulePINVOKE.delete_WeightedUTF8StringListSwig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WeightedUTF8StringListSwig(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueUTF8StringSwig element in c) {
      this.Add(element);
    }
  }

  public WeightedUTF8StringListSwig(global::System.Collections.Generic.IEnumerable<WeightedValueUTF8StringSwig> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueUTF8StringSwig element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public WeightedValueUTF8StringSwig this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(WeightedValueUTF8StringSwig[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(WeightedValueUTF8StringSwig[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, WeightedValueUTF8StringSwig[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public WeightedValueUTF8StringSwig[] ToArray() {
    WeightedValueUTF8StringSwig[] array = new WeightedValueUTF8StringSwig[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<WeightedValueUTF8StringSwig> global::System.Collections.Generic.IEnumerable<WeightedValueUTF8StringSwig>.GetEnumerator() {
    return new WeightedUTF8StringListSwigEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new WeightedUTF8StringListSwigEnumerator(this);
  }

  public WeightedUTF8StringListSwigEnumerator GetEnumerator() {
    return new WeightedUTF8StringListSwigEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class WeightedUTF8StringListSwigEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<WeightedValueUTF8StringSwig>
  {
    private WeightedUTF8StringListSwig collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public WeightedUTF8StringListSwigEnumerator(WeightedUTF8StringListSwig collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public WeightedValueUTF8StringSwig Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (WeightedValueUTF8StringSwig)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public WeightedUTF8StringListSwig() : this(IpIntelligenceEngineModulePINVOKE.new_WeightedUTF8StringListSwig__SWIG_0(), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedUTF8StringListSwig(WeightedUTF8StringListSwig other) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedUTF8StringListSwig__SWIG_1(WeightedUTF8StringListSwig.getCPtr(other)), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_Clear(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(WeightedValueUTF8StringSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_Add(swigCPtr, WeightedValueUTF8StringSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_size(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_empty(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_capacity(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_reserve(swigCPtr, n);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedUTF8StringListSwig(int capacity) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedUTF8StringListSwig__SWIG_2(capacity), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private WeightedValueUTF8StringSwig getitemcopy(int index) {
    WeightedValueUTF8StringSwig ret = new WeightedValueUTF8StringSwig(IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_getitemcopy(swigCPtr, index), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private WeightedValueUTF8StringSwig getitem(int index) {
    WeightedValueUTF8StringSwig ret = new WeightedValueUTF8StringSwig(IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_getitem(swigCPtr, index), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, WeightedValueUTF8StringSwig val) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_setitem(swigCPtr, index, WeightedValueUTF8StringSwig.getCPtr(val));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(WeightedUTF8StringListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_AddRange(swigCPtr, WeightedUTF8StringListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedUTF8StringListSwig GetRange(int index, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_GetRange(swigCPtr, index, count);
    WeightedUTF8StringListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedUTF8StringListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, WeightedValueUTF8StringSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_Insert(swigCPtr, index, WeightedValueUTF8StringSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, WeightedUTF8StringListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_InsertRange(swigCPtr, index, WeightedUTF8StringListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_RemoveAt(swigCPtr, index);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_RemoveRange(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public static WeightedUTF8StringListSwig Repeat(WeightedValueUTF8StringSwig value, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_Repeat(WeightedValueUTF8StringSwig.getCPtr(value), count);
    WeightedUTF8StringListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedUTF8StringListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_Reverse__SWIG_0(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_Reverse__SWIG_1(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, WeightedUTF8StringListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedUTF8StringListSwig_SetRange(swigCPtr, index, WeightedUTF8StringListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
