//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

internal class WeightedStringListSwig : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<WeightedValueStringSwig>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WeightedStringListSwig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WeightedStringListSwig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WeightedStringListSwig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WeightedStringListSwig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IpIntelligenceEngineModulePINVOKE.delete_WeightedStringListSwig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WeightedStringListSwig(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueStringSwig element in c) {
      this.Add(element);
    }
  }

  public WeightedStringListSwig(global::System.Collections.Generic.IEnumerable<WeightedValueStringSwig> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (WeightedValueStringSwig element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public WeightedValueStringSwig this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(WeightedValueStringSwig[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(WeightedValueStringSwig[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, WeightedValueStringSwig[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public WeightedValueStringSwig[] ToArray() {
    WeightedValueStringSwig[] array = new WeightedValueStringSwig[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<WeightedValueStringSwig> global::System.Collections.Generic.IEnumerable<WeightedValueStringSwig>.GetEnumerator() {
    return new WeightedStringListSwigEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new WeightedStringListSwigEnumerator(this);
  }

  public WeightedStringListSwigEnumerator GetEnumerator() {
    return new WeightedStringListSwigEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class WeightedStringListSwigEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<WeightedValueStringSwig>
  {
    private WeightedStringListSwig collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public WeightedStringListSwigEnumerator(WeightedStringListSwig collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public WeightedValueStringSwig Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (WeightedValueStringSwig)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public WeightedStringListSwig() : this(IpIntelligenceEngineModulePINVOKE.new_WeightedStringListSwig__SWIG_0(), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedStringListSwig(WeightedStringListSwig other) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedStringListSwig__SWIG_1(WeightedStringListSwig.getCPtr(other)), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_Clear(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(WeightedValueStringSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_Add(swigCPtr, WeightedValueStringSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_size(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_empty(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_capacity(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_reserve(swigCPtr, n);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedStringListSwig(int capacity) : this(IpIntelligenceEngineModulePINVOKE.new_WeightedStringListSwig__SWIG_2(capacity), true) {
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  private WeightedValueStringSwig getitemcopy(int index) {
    WeightedValueStringSwig ret = new WeightedValueStringSwig(IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_getitemcopy(swigCPtr, index), true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private WeightedValueStringSwig getitem(int index) {
    WeightedValueStringSwig ret = new WeightedValueStringSwig(IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_getitem(swigCPtr, index), false);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, WeightedValueStringSwig val) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_setitem(swigCPtr, index, WeightedValueStringSwig.getCPtr(val));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(WeightedStringListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_AddRange(swigCPtr, WeightedStringListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedStringListSwig GetRange(int index, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_GetRange(swigCPtr, index, count);
    WeightedStringListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedStringListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, WeightedValueStringSwig x) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_Insert(swigCPtr, index, WeightedValueStringSwig.getCPtr(x));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, WeightedStringListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_InsertRange(swigCPtr, index, WeightedStringListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_RemoveAt(swigCPtr, index);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_RemoveRange(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public static WeightedStringListSwig Repeat(WeightedValueStringSwig value, int count) {
    global::System.IntPtr cPtr = IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_Repeat(WeightedValueStringSwig.getCPtr(value), count);
    WeightedStringListSwig ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightedStringListSwig(cPtr, true);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_Reverse__SWIG_0(swigCPtr);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_Reverse__SWIG_1(swigCPtr, index, count);
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, WeightedStringListSwig values) {
    IpIntelligenceEngineModulePINVOKE.WeightedStringListSwig_SetRange(swigCPtr, index, WeightedStringListSwig.getCPtr(values));
    if (IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Pending) throw IpIntelligenceEngineModulePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
