@GettingStarted_API_HostAddress = http://localhost:5225

###
GET {{GettingStarted_API_HostAddress}}/download-ipi-gz
###
GET {{GettingStarted_API_HostAddress}}/accessibleproperties
Accept: application/json
###
GET {{GettingStarted_API_HostAddress}}/accessibleproperties/KEY-PROPS
Accept: application/json
###
GET {{GettingStarted_API_HostAddress}}/evidencekeys
Accept: application/json
###
GET {{GettingStarted_API_HostAddress}}/evidencekeys/KEY-KEYS
Accept: application/json
###
GET {{GettingStarted_API_HostAddress}}/json?client-ip=8.132.215.46
Accept: application/json
###
POST {{GettingStarted_API_HostAddress}}/json
Accept: application/json
Content-Type: application/x-www-form-urlencoded

resource=KEY2&client-ip=16.52.73.94
###
GET {{GettingStarted_API_HostAddress}}/KEY3.json?client-ip=18.132.215.46
Accept: application/json
###
POST {{GettingStarted_API_HostAddress}}/KEY4.json
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client-ip=116.52.73.94
###
