name: Nightly Pull Requests

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false
      skip-compare-performance:
        description: '🦆 Performance'
        type: boolean
        default: false

jobs:
  NightlyPullRequests:
    uses: 51Degrees/common-ci/.github/workflows/nightly-pull-requests.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      skip-compare-performance: ${{ inputs.skip-compare-performance || false }}
      build-test-timeout-minutes: 300
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.IPI_DATA_FILE_URL }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      AcceptCHBrowserKey: ${{ secrets.ACCEPTCH_BROWSER_KEY}}
      AcceptCHHardwareKey: ${{ secrets.ACCEPTCH_HARDWARE_KEY}}
      AcceptCHPlatformKey: ${{ secrets.ACCEPTCH_PLATFORM_KEY}}
      AcceptCHNoneKey: ${{ secrets.ACCEPTCH_NONE_KEY}}
