name: Nightly Pipeline

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false
      skip-compare-performance:
        description: '🦆 Performance'
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * *'

jobs:
  DataFileChange:
    name: Nightly Data File Change
    uses: 51Degrees/common-ci/.github/workflows/nightly-data-file-change.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      data-type: "IpIntelligence"
      data-product: "EnterpriseV4"
      data-filename: "51Degrees-EnterpriseV4.ipi.gz"
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      data-key: ${{ secrets.DEVICE_DETECTION_KEY }}
      data-url: ${{ secrets.IPI_DATA_FILE_URL }}

  PackageUpdate:
    name: Nightly Package Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  SubmoduleUpdate:
    name: Nightly Submodule Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-submodule-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  PullRequests:
    if: ${{ !cancelled() }}
    needs: [DataFileChange, PackageUpdate, SubmoduleUpdate]
    name: Nightly Pull Requests
    uses: 51Degrees/common-ci/.github/workflows/nightly-pull-requests.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      skip-compare-performance: ${{ inputs.skip-compare-performance || false }}
      build-test-timeout-minutes: 300
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.IPI_DATA_FILE_URL }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      AcceptCHBrowserKey: ${{ secrets.ACCEPTCH_BROWSER_KEY}}
      AcceptCHHardwareKey: ${{ secrets.ACCEPTCH_HARDWARE_KEY}}
      AcceptCHPlatformKey: ${{ secrets.ACCEPTCH_PLATFORM_KEY}}
      AcceptCHNoneKey: ${{ secrets.ACCEPTCH_NONE_KEY}}

  Publish:
    if: ${{ !cancelled() }}
    needs: PullRequests
    name: Nightly Publish
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      skip-compare-performance: ${{ inputs.skip-compare-performance || false }}
      build-platform: windows-latest
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      ApiKey: ${{ secrets.NUGET_API_KEY }}
      CodeSigningKeyVaultUrl: ${{ secrets.CODE_SIGNING_KEY_VAULT_URL }}
      CodeSigningKeyVaultClientId: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_ID }}
      CodeSigningKeyVaultTenantId: ${{ secrets.CODE_SIGNING_KEY_VAULT_TENANT_ID }}
      CodeSigningKeyVaultClientSecret: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_SECRET }}
      CodeSigningKeyVaultCertificateName: ${{ secrets.CODE_SIGNING_KEY_VAULT_CERTIFICATE_NAME }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.IPI_DATA_FILE_URL }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      AcceptCHBrowserKey: ${{ secrets.ACCEPTCH_BROWSER_KEY}}
      AcceptCHHardwareKey: ${{ secrets.ACCEPTCH_HARDWARE_KEY}}
      AcceptCHPlatformKey: ${{ secrets.ACCEPTCH_PLATFORM_KEY}}
      AcceptCHNoneKey: ${{ secrets.ACCEPTCH_NONE_KEY}}
