name: Nightly Data File Change

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so quote this string
    - cron:  '0 0 * * *'


jobs:
  # Run the common workflow on each pull request
  Nightly_Data_File_Change:
    uses: 51Degrees/common-ci/.github/workflows/nightly-data-file-change.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      data-type: "IpIntelligence"
      data-product: "EnterpriseV4"
      data-filename: "51Degrees-EnterpriseV4.ipi.gz"
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      data-key: ${{ secrets.IP_INTELLIGENCE_KEY }}
      data-url: ${{ secrets.IP_INTELLIGENCE_URL }}
