name: Nightly Package Update

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so quote this string
    - cron:  '0 0 * * *'

jobs:
  Nightly_Package_Update:
    uses: 51Degrees/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      common-ci-ref: 554f3a9e83185d59f4b43e9c6ab3582a2b7b1e58
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
